name: Remind user to run migrations

on:
  pull_request:
    types: [closed]

jobs:
  list_changed_files:
    name: Remind user to run migrations if /migrations folder was modified.
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Fetch repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get changed files in the migrations folder
        id: changed-migration-files
        uses: tj-actions/changed-files@v32
        with:
          files: |
            webapp/migrations/**
      - name: Comment on PR if migrations folder changed
        if: steps.changed-migration-files.outputs.any_changed == 'true'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            @${{ github.actor }} remember to run migrations for this PR!
