name: Check for changes to migrations folder
on:
  pull_request:
    types:
      - closed
    paths:
      - webapp/migrations/**
jobs:
  remind_user_about_migrations:
    name: Remind user to run migrations if /migrations folder was modified.
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR if migrations folder changed
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            @${{ github.actor }} remember to run migrations for this PR!
